### ISSUE TITLE
RT the first tweet of reply (bug)

### ISSUE THREAD

**Issue by antrussolillo** [social-manager-tools/twitter-bot.js#6]
### Versions

Replace the values below with your own:

- **Bot Version:** v0.7.0
- **Node Version:** v8.9 (Bot require >= 7.6)
- **Operating System:** Mac HighSierra 10.13.6
- **Browser:** Google Chrome 64

### Expected Behavior

RT of post with specific hashtag

### Actual Behavior

The RT also occurs for posts that have nothing to do with the hashtags shown
<img width="604" alt="schermata 2018-08-28 alle 13 12 10" src="https://user-images.githubusercontent.com/42771044/44737937-aa8de180-aaf3-11e8-93de-fffc9a6ce235.png">
<img width="618" alt="schermata 2018-08-28 alle 13 12 19" src="https://user-images.githubusercontent.com/42771044/44737940-aa8de180-aaf3-11e8-92c7-8563a1cfbb5b.png">
<img width="1006" alt="schermata 2018-08-28 alle 13 15 22" src="https://user-images.githubusercontent.com/42771044/44737941-aa8de180-aaf3-11e8-93bb-e581cb25f3ed.png">

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### config.js (remember to remove password)
```

```

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by ptkdev** [comment]
Fixed in **`0.5.1`** of Social Manager Tools

<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
